### ISSUE TITLE
Keep menu is open every time I open Popup for Keep

### ISSUE THREAD

**Issue by JVimes** [claudiodangelis/popup-for-keep#27] opened 2016-07-18 17:53 UTC
Every time I open Popup for Keep, the Keep side-menu is open, covering my notes.

![2016-07-18_11h50_49](https://cloud.githubusercontent.com/assets/6148201/16924801/429f0b64-4cde-11e6-841e-65c2b6e01956.png)

**Comment by claudiodangelis** [comment] 2016-07-18 18:28
Hi, thanks for reporting. 

This is a known issue which is already tracked here: https://github.com/claudiodangelis/popup-for-keep/issues/26

I hope to get it fixed in a few days!

I'm closing this issue as it's a duplicate of #26.

**Comment by claudiodangelis** [comment] 2016-07-20 12:56
Hello @JVimes, the issue is fixed now as of version 0.6.2 .
Thanks for reporting!

**Comment by JVimes** [comment] 2016-07-20 15:10
Thanks! That was so fast. I see it working in production. :+1:

**Comment by JVimes** [comment] 2016-07-26 21:52
@claudiodangelis , I think this still needs to be fixed for the pop-out window.

**Comment by claudiodangelis** [comment] 2016-07-26 21:53
Oh, very good point! I totally forgot about it, to be honest. Thanks!

**Comment by claudiodangelis** [comment] 2016-07-27 11:50
Hi @JVimes , I just released 0.6.3 which resolves the issue. If you can, please feel free to confirm it's working correctly now.

**Comment by JVimes** [comment] 2016-07-27 18:03
Hmm, I'm not seeing it in production. It shows v0.6.3 in the about box. I uninstalled Popup, relaunched Chrome, and reinstalled Popup for Keep. Tried clearing cache. Does it load the same version in the pop-out window?

Also noticed a broken image:
![image](https://cloud.githubusercontent.com/assets/6148201/17186296/dce8c60a-53f1-11e6-8b23-365e7bc6e54a.png)

**Comment by claudiodangelis** [comment] 2016-07-28 14:00
Ok, I release another update now, it should be able to actually close the sidebar now.
As per the other issue reported (broken image link), that should be solved as well.

The new version, 0.6.4, has been just submitted to Google Chrome Web Store and it can take up to 60 minutes from now to be available to the public.

Thanks!

**Comment by JVimes** [comment] 2016-07-29 14:45
Thanks, @claudiodangelis! The side bar is now fixed in the popout window. 

The image still isn't showing up for me, but looks like this:
![image](https://cloud.githubusercontent.com/assets/6148201/17252178/2f81ecae-5571-11e6-8cbf-c1bd60e4d6b6.png)

**Comment by claudiodangelis** [comment] 2016-07-29 14:51
John,

great to hear :-)
The other issue is tricky, it's technically resolved, but you are still
experiencing because the extension is picking up bad cached data.
You could either clear your cache and restart the browser, or wait for me
to implement a "Clear Extension Cache" button in the Options page if you
don't want to clear full browser cache.

I'm closing this issue, thanks for the help!

Claudio



Claudio d'Angelis

claudiodangelis@gmail.com
Skype: claudiodangelis
Phone: (+39) 329 2933194



2016-07-29 16:45 GMT+02:00 John Burak <notifications@github.com>:

**Closed** 2016-07-29 14:51 UTC

**Comment by JVimes** [comment] 2016-07-29 15:09
Hmm, today, the broken image is on a machine that had never loaded the extension before today. The src attribute for the image has no value. Maybe that's it?

```
<img id="img-account" alt="Avatar" src="">
```

**Comment by claudiodangelis** [comment] 2016-07-29 15:12
Ah, interesting.

Please let me ask, do you see your correct email address in the Options
page in the "Accounts" section?

Thanks,

Claudio d'Angelis

claudiodangelis@gmail.com
Skype: claudiodangelis
Phone: (+39) 329 2933194



2016-07-29 17:09 GMT+02:00 John Burak <notifications@github.com>:

**Comment by JVimes** [comment] 2016-07-29 15:21
Oh, I do, but my avatar image is empty there, too ;) Are avatars being pulled, ultimately, from Google+? If so, it's not a bug. I disabled my Google+ profile. I do have a Gmail avatar.

**Comment by claudiodangelis** [comment] 2016-07-29 15:26
Oh, got it. Avatars should be showing up, here's what I see with mine:

![https://screen.claudiodangelis.com/GoDM6pN8rfprPJvJom4czKZ8u8NrhLro.png](https://screen.claudiodangelis.com/GoDM6pN8rfprPJvJom4czKZ8u8NrhLro.png)

There must be something wrong in the code that scrapes the image URL, then. I will investigate this issue in a couple weeks!
